# ===============================
# CONFIGURAÇÃO DO BANCO DE DADOS (Salvando em Arquivo físico)
# ===============================
spring.datasource.url=jdbc:h2:file:./dados_salvos/edugamedb;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ===============================
# CONFIGURAÇÃO DO HIBERNATE / JPA
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# "update" diz ao Java para APENAS ATUALIZAR o banco, e nunca apagar o que já existe.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true

# ===============================
# CONSOLE DO H2 (Acesso pelo navegador)
# ===============================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true