# 1. IMPORTAR O COFRE PRIMEIRO!
spring.config.import=optional:file:segredos.properties
# ===============================
# CONFIGURAÇÃO DO BANCO DE DADOS
# ===============================
spring.datasource.url=jdbc:h2:file:./dados_salvos/edugamedb;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ===============================
# CONFIGURAÇÃO DO HIBERNATE / JPA
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true

# ===============================
# CONSOLE DO H2
# ===============================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# ===============================
# CONFIGURAÇÃO DE ENVIO DE E-MAIL (GMAIL)
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
# O Java agora vai conseguir ler isto lá do .env.properties!
spring.mail.username=${EMAIL_JOGO}
spring.mail.password=${SENHA_JOGO}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.debug=true