# ==========================================
# ⚙️ CONFIGURAÇÃO DO BANCO DE DADOS H2 (MEMÓRIA)
# ==========================================
spring.datasource.url=jdbc:h2:mem:edugamedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Habilita o painel do H2 no navegador para você ver suas tabelas depois
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ==========================================
# 🛠️ CONFIGURAÇÃO DO HIBERNATE (JPA)
# ==========================================
# Cria e atualiza as tabelas automaticamente baseado nas suas classes Java
spring.jpa.hibernate.ddl-auto=update

# Mostra no terminal os comandos SQL que o Spring está fazendo por baixo dos panos (ótimo para debugar)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Evita conflitos na hora de carregar dados iniciais
spring.jpa.defer-datasource-initialization=true